name: Desplegar a producción

on:
  push:
    branches:
      - master

jobs:
  web-deploy:

    name: Desplegar web LugoGamingFest
    runs-on: ubuntu-latest

    env:
      SERVER: lugogamingfest.es

    steps:
    - name: Obtenemos la ultima version de codigo
      uses: actions/checkout@v2.3.2

    - name: Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar NPM Modules
      run: npm install

    - name: Compilar proyecto
      run: npm run ng build

    - name: Enviar a FTP produccion
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.SERVER }}
        username: ${{ secrets.PROD_USER }}
        password: ${{ secrets.PROD_PASSWORD }}
        local-dir: dist/LugoGamingFestWeb/
        server-dir: /domains/lugogamingfest.es/public_html/
        dangerous-clean-slate: true
