name: Deploy prod site on push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    env:
      SERVER: lugogamingfest.es

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run ng build --prod

    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.SERVER }}
        username: ${{ secrets.PROD_USER }}
        password: ${{ secrets.PROD_PASSWORD }}
        local-dir: ./dist/
        server-dir: /domains/lugogamingfest.es/public_html/
        dangerous-clean-slate: true
